# example docker compose file used on a nas to run api.
# need to create the network first and this assumes a mongodb container is running called 'cortext-mongo'
services:
  mediaset-api:
    image: mediaset-api:latest
    container_name: cortext-mediaset
    restart: always
    ports:
      - 7134:8080
    networks:
      - mediaset
    environment:
      "MediaSetDatabase:ConnectionString": "mongodb://cortext-mongo:27017"
      "MediaSetDatabase:DatabaseName": "MediaSet"
      "OpenLibraryConfiguration:BaseUrl": "https://openlibrary.org/"
      # "OpenLibraryConfiguration:Timeout": "30"
      # "OpenLibraryConfiguration:ContactEmail": "me@paulmfischer.dev"
      # Barcode Lookup API - Get key from: https://www.barcodelookup.com/api
      # "BarcodeLookupConfiguration:BaseUrl": "https://api.barcodelookup.com/v3/"
      # "BarcodeLookupConfiguration:ApiKey": "YOUR_BARCODE_LOOKUP_API_KEY"
      # "BarcodeLookupConfiguration:Timeout": "30"
      # TMDb API - Get key from: https://www.themoviedb.org/settings/api
      # "TmdbConfiguration:BaseUrl": "https://api.themoviedb.org/3/"
      # "TmdbConfiguration:ApiKey": "YOUR_TMDB_API_KEY"
      # "TmdbConfiguration:Timeout": "30"

networks:
  mediaset:
    external: true
    name: mediaset